sudo : required

language : generic

services:
  - docker

before_install:
  - echo "Start Creating an image with dockerfile"
  - docker build -t frostscent/react-app -f dockerfile.dev .

script:
  - docker run -e CI=true frostscent/react-app npm run test -- --coverage

after_success:
  - echo "Test Success"