sudo : required

language : generic

services:
  - docker

before_install:
  - echo "Start Creating an image with Dockerfile"
  - docker build -t frostscent/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true frostscent/react-app npm run test -- --coverage

# after_success:
#   - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-404986612989"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY